apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

nameSuffix: -peer-pods

resources:
- ../base

images:
- name: quay.io/confidential-containers/reqs-payload
  newTag: c31205eb31d8a4623ffc0c9fa316e3c91e337023
- name: quay.io/confidential-containers/runtime-payload
  newName: quay.io/confidential-containers/runtime-payload-ci
  newTag: kata-containers-4089d48b4532139e361af8f3b84d97d25f57d9c2

patches:
- patch: |-
    - op: replace
      path: /spec/config/runtimeClasses
      value:
      - name: "kata-remote"
        snapshotter: "nydus"
    - op: add
      path: /spec/config/debug
      value: false
    - op: add
      path: /spec/config/environmentVariables
      value:
        # It means that we're relying on the cluster to already have
        # containerd v1.7+ running.  If you know for sure that's not
        # the case, please, set this variable to `true`
        - name: "INSTALL_OFFICIAL_CONTAINERD"
          value: "true"
  target:
    kind: CcRuntime
